### ISSUE TITLE
[feature]: support parsing comments in documents

### ISSUE THREAD

**Issue by ssteinbach** [kubkon/zig-yaml#5]
I'm trying to open a yaml document like:

```yaml
test_string: "hello!"
# this is a comment
other_thing: 12
```

If I remove the comment, the parse is successful, but if it is present, the parser errors with an unexpected token.  Looking through the code it definitely seems to have references to comments, but I didn't see any in the yaml files in the repo, so I thought I would ask.

The error:
```
zig-yaml/src/parse.zig:339:21: 0x103042b55 in .yaml.parse.Parser.doc (visualizer)
                    return error.UnexpectedToken;
```

Thanks!
