### ISSUE TITLE
Incorrectly parsing file

### ISSUE THREAD

**Issue by biom4st3r** [kubkon/zig-yaml#52]
I'm using Yaml for Dialogue in my game and I have this chunk at the start.

```
---
captain_dispatch:
  - dtype: Dispatch
    ddata: captain_startq1
    requires:
      rtype: NotFlag
      rdata: quest1_started
  - dtype: Dispatch
    ddata: captain_quest1_3getfish
    requires:
      rtype: All
      rdata:
        - rtype: Flag
          rdata: quest1_3getfish
        - rtype: Item
          rdata:
            item: 1
            count: 1

  - dtype: Dispatch
    ddata: captain_quest2_2talktocaptain
    requires:
      rtype: Flag
      rdata: quest2_2talktocaptain
  - dtype: Text
    ddata:
      - title: Captain
        text: Have fun fishing! I know I will.
```
Each of the root keys(captain_dispatch) has a list of dialogue steps that have a `dtype` and `ddata`.  The `requires` field is optional and here is how I parse it
```
    pub fn decode(entry: y.Value) AbstractStep {
...
        var req: y.Value = y.Value{ .empty = {} };
...
        if (entry.map.get("requires")) |v| req = v;

        std.debug.assert(req == .empty or req == .map);
        return AbstractStep{
...
            .requirement = if (req != .empty) IRequire.decode(req) else IRequire.default(),
        };

```

When I find the correct rtype i print the rdata with `rdata.stringify(std.io.getStdOut().writer(), .{}) catch unreachable;`

BUT the rdata I get for the second dialogue step(ddata: captain_quest1_3getfish) is:
```
- rtype: Flag
  rdata: quest1_3getfish
- rtype: Item
  rdata:
      item: 1
      count: 1
- dtype: Dispatch
  ddata: captain_quest2_2talktocaptain
  requires:
      rtype: Flag
      rdata: quest2_2talktocaptain
- dtype: Text
  ddata:
      - title: Captain
        text: Have fun fishing! I know I will.quest1_3getfishitem: 1
```
It seems to be parsing steps 3(captain_quest2_2talktocaptain) and step 4 as if they are in the `requires` list for step 2
In fact when I print the `map.keys` for one of the items in the `rtype: All` list i get
```
debug: KEY: dtype
debug: KEY: ddata
debug: KEY: requires
```
