### ISSUE TITLE
Respect Struct's default values

### ISSUE THREAD

**Issue by Gnyblast** [kubkon/zig-yaml#85]
Assume that I have following struct:
```zig
pub const MasterServerConf = struct {
    host: []const u8 = "127.0.0.1",
    port: u16 = 7423,
    type: []const u8 = "tcp",
    time_zone: ?[]const u8 = "UTC",
};
```

and following yaml file:
```yaml
server:
  host: "127.0.0.1"
  port: 7423
  type: tcp
```
When let's say `time_zone` not exist in yaml config, even though it has default value, the parsed overrides it to `null`. Is it possible to not override when a non-existing optional field has a default value in struct?
